config/routes.rb
Rails.application.routes.draw do
  root 'homepages#index'
  resources :users
  resources :customers
  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :restaurants do
    resources :reservations
  end
  

end

app/models/customer.rb
class Customer < User
	has_many :reservations
	has_many :reviews
	belongs_to :user
end

app/models/owner.rb
class Owner < User
	has_many :restaurants
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :customer

	validate :availability

	def pretty_book_time
		book_time.strftime("%I %p ")
	end

	private
	def availability
		unless restaurant.available?(party_size, book_time)
			errors.add(:base, "Restaurant not available.")
			# errors.add(:book_time, " is fully booked at this time")
		end
	end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :reviews
	belongs_to :owner

	def available?(party_size, book_time)
		# 2:21 vs 2:00
		reserved = reservations.where(:book_time => book_time).sum(:party_size)
		if (party_size <= (capacity - reserved)) && (book_time.hour.between?(open_time.hour, close_time.hour))
			return true
		else 
			return false
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :customers
	has_many :owners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def ensure_owner
   	if !current_user || (current_user && !current_user.type == "Owner")
  		redirect_to new_session_path
  	end
  end

  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def show
		@customer = User.find(params[:id])
	end

	def edit
		@customer = User.find(params[:id])
	end

	def update
		@customer = User.find(params[:id])
		if @customer.update_attributes(customers_params)
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		@customer = User.find(params[:id])
		@customer.destroy
		redirect_to users_path
	end

	private
	def customers_params
		params.require(:customer).permit(:name, :email)
	end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	def index
		
	end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
	def show
		@owner = User.find(params[:id])
	end

	def edit
		@owner = User.find(params[:id])
	end

	def update
		@owner = User.find(params[:id])
		if @owner.update_attributes(owners_params)
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		@owner = User.find(params[:id])
		@owner.destroy
		redirect_to users_path
	end

	private
	def owners_params
		params.require(:owner).permit(:name, :email)
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def show
		@reservation = Reservation.find(params[:id])
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])

		# This is the equivalent of the .build method
		# @reservation = Reservation.new(reservation_params)
		# @reservation.restaurant = @restaurant 

		@reservation = @restaurant.reservations.build(reservation_params)

		@user = @restaurant.owner

		if @reservation.save
			redirect_to restaurants_path, notice: "Reservation created successfully"
		else
			render 'restaurants/show'
		end
	end

	private
	def reservation_params
		params.require(:reservation).permit(:date, :party_size, :book_time, :customer_id)
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_filter :ensure_owner, only: [:new, :create]

	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		unless current_user.nil?
			if current_user.type == "Customer"
				@reservation = @restaurant.reservations.build
			end
		end
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		@restaurant.owner_id = current_user.id
		if @restaurant.save
			redirect_to restaurant_path(@restaurant)
		else
			render :new
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.update_attributes(restaurant_params)
			redirect_to restaurants_path
		else
			render :edit
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_path
	end

	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :location, :owner_id, :capacity, :open_time, :close_time, :description, :picture)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	user = User.find_by(email: params[:email])
  	if user && user.type == "Owner" && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to owner_path(user), notice: "Logged in as Owner!"
  	elsif user && user.type == "Customer" && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to customer_path(user), notice: "Logged in as Customer!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save && @user.type == "Owner"
			session[:user_id] = @user.id
			redirect_to new_restaurant_path
		elsif @user.save && @user.type == "Customer"
			session[:user_id] = @user.id
			redirect_to restaurants_path
		else
			render :new
		end
	end

	# def edit
	# 	@user = User.find(params[:id])
	# end

	# def update
	# 	@user = User.find(params[:id])
	# 	if @user.update_attributes(user_params)
	# 		redirect_to users_path
	# 	else
	# 		render :new
	# 	end
	# end

	# def destroy
	# 	@user = User.find(params[:id])
	# 	@user.destroy
	# 	redirect_to users_path
	# end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :type)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/edit.html.erb
<div class="container">
	<h1>Edit Customer</h1>
	<%= form_for(@customer) do |f| %>
		<%= f.text_field :name, placeholder: "Name", class: "form_fields" %><br>
		<%= f.text_field :email, placeholder: "Email", class: "form_fields" %><br>
		<%= f.submit class: "form_fields" %>
	<% end %>
</div>

app/views/customers/show.html.erb
<div class="container">
	<h1><%= @customer.name %></h1>
	<%= link_to "Edit", edit_customer_path %>
	<%#= link_to "Delete", @customer, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>

	<p>
		Email: <%= @customer.email %><br>
	</p>

	<h1>Upcoming reservations</h1>

	<div class="row marketing">
		<% @customer.reservations.each do |res| %>
		<div class="col-lg-6">
			<h4><%= link_to res.restaurant.name, restaurant_path(res.restaurant) %></h4>
			<p>Date: <%= res.date %><br>
				Book time: <%= res.pretty_book_time %><br>
				Party size: <%= res.party_size %><br></p>
			</div>
			<% end %>
		</div>

		<%= link_to "Show all restaurants", restaurants_path %>

app/views/homepages/index.html.erb
<div class="jumbotron">
			<h1>Welcome to <br>Seat Yourself</h1>
			<p class="lead">This is a restaurant reservation app to easily book a table for you at your favorite restaurant.</p>
			<% unless current_user %>
			<p><%= link_to "Signup", new_user_path, class: "navbar-brand", class: "btn btn-lg btn-success" %></p>
			<% end %>
		</div>
		</div>

app/views/owners/edit.html.erb
<%= form_for(@owner) do |f| %>
	<%= f.text_field :name, placeholder: "Name" %>
	<%= f.text_field :email, placeholder: "Email" %>
	<%= f.submit %>
<% end %>

app/views/owners/show.html.erb
<h1>Display owner</h1>
<%= link_to "Edit", edit_owner_path %> | 
<%= link_to "Delete", @owner, method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %>

<p>
	Name: <%= @owner.name %><br>
	Email: <%= @owner.email %><br>
	ID: <%= @owner.id %><br>
	Type: <%= @owner.type %>
</p>

 <%= link_to "Create Restaurant", new_restaurant_path %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
	<%= f.text_field :name, placeholder: "Name" %><br>
	<%= f.text_field :picture, placeholder: "Image URL" %> <br>
	<%= f.text_area :description, placeholder: "Description" %><br>
	<%= f.text_field :location, placeholder: "Location" %><br>
	<%= f.number_field :capacity, placeholder: "Capacity" %><br>
	Open time: <%= f.time_field :open_time %><br>
	Close time: <%= f.time_field :close_time %><br>
	<%= f.submit class: "form_fields" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>
<%= link_to "List of restaurants", restaurants_path %> |
<%= link_to "Delete", @restaurant, method: :delete, data: { confirm: "Are you sure you want to delete this restaurant?" } %>

<%= render "form" %>

app/views/restaurants/index.html.erb
<h2 id="tables-hover-rows">All Restaurants</h2>
<div class="bs-example" data-example-id="hoverable-table">
	<% @restaurants.each do |restaurant|%>
	<table class="table table-hover">
		<tbody>
			<tr>
				<td class="col-md-3" > <img src="<%=restaurant.picture %>" alt=""></td>
				<td class="col-md-3"><%= link_to restaurant.name, restaurant_path(restaurant) %> </td>
				<td class="col-md-3"><%= restaurant.location %> </td>
				<td class="col-md-3"><%= restaurant.description %> </td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
	<h1>Create new restaurant</h1>

	<%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
	<h1><%= @restaurant.name %></h1>
	<%= @restaurant.location %>

	<% if @restaurant.open_time && @restaurant.close_time %>
	<p>Hours: <%= @restaurant.open_time.hour %> to <%= @restaurant.close_time.hour %> </p>
	<% end %>

	<% if current_user.nil? || current_user.type == "Owner" %>
	<p>Please sign up/Login to make a reservation</p>
	<% else %>
	<h1>Create A Reservation</h1>
	<%= form_for([@restaurant, @reservation]) do |f| %>
	<% if @reservation.errors.any? %>
	<h2><%= @reservation.errors.full_messages.first %></h2> 
	<% end %>

	Date of reservation: <%= f.datetime_select :book_time,  start_hour: @restaurant.open_time.hour, discard_minute: true, class: "form_fields" %><br>
	<%= f.date_field :date, class: "form_fields" %><br>
	<%= f.hidden_field 'customer_id', value: current_user.id %>
	<%= f.number_field :party_size, placeholder: "Party size", class: "form_fields" %><br>
	<%= f.submit class: "form_fields" %>
	<% end %>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= f.text_field :name, placeholder: "Name", class: "form_fields" %><br>
	<%= f.text_field :email, placeholder: "Email", class: "form_fields" %><br>
	<%= f.password_field :password, placeholder: "Password", class: "form_fields" %><br>
	<%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form_fields" %><br>
	<select name="user[type]", class="form_fields">
		<option value="Customer">Customer </option>
		<option value="Owner">Owner </option>
	</select><br>
	<%= f.submit class: "form_fields" %>
<% end %>

app/views/users/index.html.erb
<div class ="users_container">
	<h1>All users</h1>
	<table class="restaurants_table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
			</tr>
		</thead>
		<% @users.each do |user| %>
			<% if user.is_a? Customer %>
				<tr>
					<td><%= link_to user.name, customer_path(user) %></td>
					<td><%= user.email %></td>
				</tr>
			<% elsif user.is_a? Owner %>
				<tr>
					<td><%= link_to user.name, owner_path(user) %></td>
					<td><%= user.email %></td>
				</tr>
			<% end %>
		<% end %>
	</table>	
</div>

app/views/users/new.html.erb
<div class="container">
	<h1>Create User</h1>
	<%= render 'form' %>
</div>