config/routes.rb
Rails.application.routes.draw do
  root 'homepages#index'
  resources :users
  resources :customers
  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :restaurants do
    resources :reservations
  end
  

end

app/models/customer.rb
class Customer < User
	has_many :reservations
	has_many :reviews
	belongs_to :user
end

app/models/owner.rb
class Owner < User
	has_many :restaurants
	belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :customer

	validate :availability

	def pretty_book_time
		book_time.strftime("%I %p ")
	end

	private
	def availability
		unless restaurant.available?(party_size, book_time)
			errors.add(:base, "Restaurant not available.")
			# errors.add(:book_time, " is fully booked at this time")
		end
	end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :reviews
	belongs_to :owner

	def available?(party_size, book_time)
		# 2:21 vs 2:00
		reserved = reservations.where(:book_time => book_time).sum(:party_size)
		if (party_size <= (capacity - reserved)) && (book_time.hour.between?(open_time.hour, close_time.hour))
			return true
		else 
			return false
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :customers
	has_many :owners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def ensure_owner
   	if !current_user || (current_user && !current_user.type == "Owner")
  		redirect_to new_session_path
  	end
  end

  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def show
		@customer = User.find(params[:id])
	end

	def edit
		@customer = User.find(params[:id])
	end

	def update
		@customer = User.find(params[:id])
		if @customer.update_attributes(customers_params)
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		@customer = User.find(params[:id])
		@customer.destroy
		redirect_to users_path
	end

	private
	def customers_params
		params.require(:customer).permit(:name, :email)
	end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	def index
		
	end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
	def show
		@owner = User.find(params[:id])
	end

	def edit
		@owner = User.find(params[:id])
	end

	def update
		@owner = User.find(params[:id])
		if @owner.update_attributes(owners_params)
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		@owner = User.find(params[:id])
		@owner.destroy
		redirect_to users_path
	end

	private
	def owners_params
		params.require(:owner).permit(:name, :email)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	user = User.find_by(email: params[:email])
  	if user && user.type == "Owner" && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to owner_path(user), notice: "Logged in as Owner!"
  	elsif user && user.type == "Customer" && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to customer_path(user), notice: "Logged in as Customer!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save && @user.type == "Owner"
			session[:user_id] = @user.id
			redirect_to new_restaurant_path
		elsif @user.save && @user.type == "Customer"
			session[:user_id] = @user.id
			redirect_to restaurants_path
		else
			render :new
		end
	end

	# def edit
	# 	@user = User.find(params[:id])
	# end

	# def update
	# 	@user = User.find(params[:id])
	# 	if @user.update_attributes(user_params)
	# 		redirect_to users_path
	# 	else
	# 		render :new
	# 	end
	# end

	# def destroy
	# 	@user = User.find(params[:id])
	# 	@user.destroy
	# 	redirect_to users_path
	# end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :type)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Table3</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<div class="header">
			<nav>
				<ul class="nav nav-pills pull-right">
				
					<li role="presentation"><%= link_to "All restaurants", restaurants_path %></li>
					
					<% if current_user %>
					<li role="presentation" class="active"><%= link_to current_user.name, current_user%></li>
					<li role="presentation"><%= link_to "Log out", session_path("current"), :method => :delete %></li>
					<% else %>
					<li role="presentation"><%= link_to "Login", new_session_path, class: "navbar-brand" %></li>
					<li role="presentation"><%= link_to "Signup", new_user_path, class: "navbar-brand"%></li>
					<% end %>
				</ul>
			</nav>
			<h3 class="text-muted"><%= link_to "Seat Yourself", root_path %> </h3>
		</div>

		<%= yield %>

		<footer class="footer">
			<p>&copy; Seat Yourself</p>
		</footer>

	</div> <!-- /container -->

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>